website1: https://test-stand.gb.ru/gateway/login
website2: https://test-stand.gb.ru/api/posts
website3: https://test-stand.gb.ru/gateway/posts
username: LenOK
password: 1a8435b14a
title1: My new post
description1: New post
content1: content
